### ISSUE TITLE
Network activation means no blocks loaded on admin page

### ISSUE THREAD

**Issue by knutsp** [front/cloud-blocks#11]
Tested on several multisite networks and if, and only if, network activated it does not load any blocks on admin Cloud Blocks page.

If activated per site it works, so it's not multisite related, but the type of activation. If per site activated first, then network activated later, it stops working, even if site activated on all the sites.

A script is not loaded on the admin page, it seems, but no console errors.

Only difference between network activation and site activation is the order of including the main plugin file, but haven't been able to find the actual reason for this strange behaviour by studying the code.

![screenshot_2019-01-10 cloud blocks nettvendt wordpress](https://user-images.githubusercontent.com/1531128/51002076-76f7a500-1532-11e9-998d-336800fafc4c.png)

**Comment by foadyousefi** [comment]
Thanks for reporting. Will look into it as soon as I can.

**Comment by foadyousefi** [comment]
The issue was global variable `$pagenow` which was used to only load plugin assets if we are in the plugin settings page. This variable seems not to work with multisite setup, at least in our case. So replaced it with `is_admin()` function and changed plugin init function just a bit. This fixed the issue for me.

Can you please check and if it solved, close this issue?

Again thanks for reporting.

**Comment by foadyousefi** [comment]
@knutsp I think the issue is solved. Can you please check and confirm?

**Comment by knutsp** [comment]
Seems to work fine now. I can see the blocks on each site.

Thanks for fixing!
